#!/usr/bin/env bash

export DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)

case "$1" in
  "start")
    docker-compose up -d
  ;;

  "follow")
    docker-compose logs -f
  ;;

  "magerun")
    docker-compose run --rm cli magento-command "${@:2}"
  ;;

  "flush")
    docker-compose run --rm cli magento-command cache:flush
    docker-compose run --rm cli magento-command cache:clear
    docker-compose restart varnish
  ;;

  "stop")
    docker-compose stop
  ;;

  "destroy")
    read -p "Are you sure? [y|N] " -n 1 -r; echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
      echo "Aborting mission... Close call!"
      exit 0
    fi

    docker-compose stop
    docker-compose rm -fv
    sudo rm -rf data/mysql \
                data/magento
esac
